name: Build ASP.NET MVC 4 (.NET 4.8)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: NuGet/setup-nuget@v1

      - run: nuget restore MedicalWebApp.sln

      - uses: microsoft/setup-msbuild@v1.3

      - run: msbuild MedicalWebApp.sln /p:Configuration=Release

      - name: Create Deployment Folder
        run: |
          mkdir deploy
          Copy-Item -Path "MedicalWebApp\bin\Release\*" -Destination deploy -Recurse

      - name: Create timestamped ZIP of build output
        run: |
          $timestamp = Get-Date -Format "dd_MM_yyyy_HH_mm"
          $zipName = "MedicalWebApp_$timestamp.zip"
          Compress-Archive -Path deploy\* -DestinationPath $zipName
          echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV
        id: build_step


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: MedicalWebApp_*.zip
