name: Build ASP.NET MVC 4 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore MedicalWebApp.sln

      - name: Install .NET Framework 4.5 Developer Pack
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/b/a/4/ba4a7e71-2906-4b2d-a0e1-80cf16844f5f/dotNetFx45_Full_setup.exe" -OutFile "ndp45-devpack.exe"
          Start-Process .\ndp45-devpack.exe -ArgumentList "/quiet" -Wait

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Build solution
        run: msbuild MedicalWebApp.sln /p:Configuration=Release
