name: Build ASP.NET MVC 4 (.NET 4.5.2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: NuGet/setup-nuget@v1

      - run: nuget restore MedicalWebApp.sln

      - name: Install .NET Framework 4.5.2 Developer Pack
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/4/3/B/43B61315-B2CE-4F5B-9E32-34CCA07B2F0E/NDP452-KB2901951-x86-x64-DevPack.exe" -OutFile "ndp452-devpack.exe"
          Start-Process .\ndp452-devpack.exe -ArgumentList "/quiet","/norestart" -Wait

      - uses: microsoft/setup-msbuild@v1.3

      - run: msbuild MedicalWebApp.sln /p:Configuration=Release
